//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jeran.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jeran.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adam; Adam is driving his motorboat when he notices five swimmers drowning in the distance. If Adam does not drive toward them at top speed he will not arrive in time, and all five will die. In order to drive at top speed, Adam must accelerate quickly. If Adam accelerates quickly, he will save the five drowning swimmers. If Adam does not accelerate quickly, the five swimmers will drown. Adam decides to accelerate quickly.;Accelerating quickly is:;.
        /// </summary>
        public static string dilemma_1 {
            get {
                return ResourceManager.GetString("dilemma_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeff ;Standing by the railroad tracks, Jeff sees an empty, out-of-control boxcar speeding toward five people. There is one person on a footbridge spanning the main tracks who is slipping and about to fall onto the main track, where he will be hit by the boxcar. The boxcar will slow down because of the one person, therefore preventing the five from being hit. Next to Jeff is a lever that can be pulled, raising the railing on the footbridge and preventing the one person from falling. If Jeff does not pull the [rest of string was truncated]&quot;;.
        /// </summary>
        public static string dilemma_10 {
            get {
                return ResourceManager.GetString("dilemma_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rick ;Rick is a fireman trying to help five children out of a burning house. There is only one window from which the children can be safely evacuated, and it is jammed shut. Rick must immediately smash open this large, heavy window or else all five children will die. Outside the window, on the sill, is a man safely awaiting evacuation who Rick cannot help hitting with his fist if he breaks the window, causing the man to fall off the sill. Falling off the sill is certain to kill the man. If Rick breaks open  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string dilemma_11 {
            get {
                return ResourceManager.GetString("dilemma_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ken; Ken is a fireman trying to help five children out of a burning house. There is only one window from which the children can be safely evacuated, and it is jammed shut. Ken must immediately smash open this large, heavy window or else all five children will die. Outside the window, on the ground below, is a man safely awaiting evacuation who Ken cannot help hitting with heavy falling glass if he breaks the window. The falling glass is certain to kill the man. If Ken breaks open the window, he will hit the [rest of string was truncated]&quot;;.
        /// </summary>
        public static string dilemma_12 {
            get {
                return ResourceManager.GetString("dilemma_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peter;Peter is a fireman trying to help five children out of a burning house. There is only one window from which the children can be safely evacuated, and it is jammed shut. Peter must immediately use an object to smash open this large, heavy window or else all five children will die. The only sufficiently large object is a man on his way towards safely escaping the burning house. Crashing through the window is certain to kill the man. If Peter pushes the man into the window and breaks it open, the man wil [rest of string was truncated]&quot;;.
        /// </summary>
        public static string dilemma_13 {
            get {
                return ResourceManager.GetString("dilemma_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andy ;Andy is a fireman trying to help five children out of a burning house. There is only one window from which the children can be safely evacuated, and it is jammed shut. Andy must immediately use an object to smash open this large, heavy window or else all five children will die. The only sufficiently large object is a man on his way towards safely escaping the burning house. Andy can break open the window by swinging a piece of burning debris towards the man, which will cause the man to jump out of the [rest of string was truncated]&quot;;.
        /// </summary>
        public static string dilemma_14 {
            get {
                return ResourceManager.GetString("dilemma_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ed ;Ed is driving five sick people to the hospital. They are in critical condition and will die if Ed makes any stops along the way. In his hurry to pack them in the car Ed slams the door on a few feet of thick cord that is now dangling beside the car. Ed takes the fastest route to the hospital, which is a narrow, unpaved mountain pass. On his way, Ed sees a rock climber hanging onto the side of the mountain beside the road. The rock climber is safe and in control, but if Ed drives by the thick cord draggin [rest of string was truncated]&quot;;.
        /// </summary>
        public static string dilemma_15 {
            get {
                return ResourceManager.GetString("dilemma_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jack ;Jack is driving five sick people to the hospital. They are in critical condition and will die if Jack makes any stops along the way. In his hurry to pack them in the car Jack slams the door on a few feet of thick cord that is now dangling beside the car. Jack takes the fastest route to the hospital, which is a narrow, unpaved mountain pass. On his way, Jack sees a rock climber hanging onto the side of the mountain beside the road. The rock climber is losing control and is about to fall to his death, b [rest of string was truncated]&quot;;.
        /// </summary>
        public static string dilemma_16 {
            get {
                return ResourceManager.GetString("dilemma_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tim ;Tim works at a hospital. He is in charge of a machine that can both increase and decrease the amount of a certain chemical in a patient&apos;s bloodstream. Too much or too little of the chemical results in death. Tim notices that the machine has pumped a near toxic amount of the chemical into a patient&apos;s body. Tim must immediately stop the machine to save the patient&apos;s life. However, he sees that five other patients with toxic amounts of the chemical are hooked up to the machine. The machine is removing the [rest of string was truncated]&quot;;.
        /// </summary>
        public static string dilemma_17 {
            get {
                return ResourceManager.GetString("dilemma_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bob ;Bob works at a hospital. He is in charge of a machine that can both increase and decrease the amount of a certain chemical in a patient&apos;s bloodstream. Too much or too little of the chemical results in death. Bob notices that the machine has pumped a near toxic amount of the chemical into a patient&apos;s body. Bob must immediately disconnect the patient to save the patient&apos;s life. However, he sees that five other patients with toxic amounts of the chemical are hooked up to the machine. The machine is removi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string dilemma_18 {
            get {
                return ResourceManager.GetString("dilemma_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to James ;James is hiking through a foreign land when he comes across a remote village. James learns that one of the villagers fell into a cursed pond but, contrary to local superstition, did not die. If the one villager does not die by sunrise, five other innocent and unwilling villagers will be sacrificed to the gods to thank them for sparing the one. James, who has some medical training, realizes that he can prevent the sacrifice of the five villagers if he secretly poisons the one villager. If James poison [rest of string was truncated]&quot;;.
        /// </summary>
        public static string dilemma_19 {
            get {
                return ResourceManager.GetString("dilemma_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ben; Ben sees that an empty runaway boxcar is headed down a track. There is nobody on the track. There is one person working on a side track. If Ben flips the switch, the boxcar will turn onto the side track and hit the one person. If Ben does not flip the switch, the boxcar will continue on the track, and nobody will be hit. Ben decides to flip the switch.;Flipping the switch is:.
        /// </summary>
        public static string dilemma_2 {
            get {
                return ResourceManager.GetString("dilemma_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robert ;Robert is hiking through a foreign land when he comes across a remote village. Robert learns that one of the villagers fell into a cursed pond but, contrary to local superstition, did not die. If the one villager does not die by sunrise, five other innocent and unwilling villagers will be sacrificed to the gods to thank them for sparing the one. Robert, who has some medical training, notices that the one has accidentally consumed a poisonous substance. Robert can administer the antidote to the one v [rest of string was truncated]&quot;;.
        /// </summary>
        public static string dilemma_20 {
            get {
                return ResourceManager.GetString("dilemma_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fred ;Fred is working on the top floor of a construction project when he sees a gearbox at the end of a steel beam is about to break. Suspended from the gearbox is an elevated platform with five workers on it, and if the gearbox breaks the five workers will fall to their deaths. Fred can save the five if he rushes across the steel beam immediately to engage the backup mechanism on the gearbox. In between Fred and the gearbox there is a worker standing on the beam. Fred knows that if he rushes across the nar [rest of string was truncated]&quot;;.
        /// </summary>
        public static string dilemma_21 {
            get {
                return ResourceManager.GetString("dilemma_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethan ;Ethan is working on the top floor of a construction project when he sees a gearbox at the end of a steel beam is about to break. Suspended from the gearbox is an elevated platform with five workers on it, and if the gearbox breaks the five workers will fall to their deaths. Ethan can save the five if he rushes across the steel beam immediately to engage the backup mechanism on the gearbox. In between Ethan and the gearbox there is a gate and a worker standing next to the gate. Ethan knows that if he  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string dilemma_22 {
            get {
                return ResourceManager.GetString("dilemma_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joe ;Joe is drifting along in his motorboat at the mouth of a narrow channel when he notices a shark approaching. Further down the channel he sees five swimmers. If Joe maintains his current position, his boat will obstruct the entrance to the channel, thereby preventing the shark from attacking the five swimmers. However, Joe sees another swimmer drowning in the distance. Joe can save the one swimmer by immediately moving toward him in the motorboat, thereby leaving the channel open to the shark. If Joe mo [rest of string was truncated]&quot;;.
        /// </summary>
        public static string dilemma_23 {
            get {
                return ResourceManager.GetString("dilemma_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casey ;Casey is drifting along in his motorboat near the mouth of a narrow channel when he notices a shark approaching. Further down the channel he sees five swimmers. However, one other swimmer is positioned at the mouth of the channel such that the shark will attack the one first, giving the five the necessary time to escape. Casey can save the one swimmer by immediately moving toward him in the motorboat, but saving the one swimmer would also leave the channel open to the shark. If Casey moves towards th [rest of string was truncated]&quot;;.
        /// </summary>
        public static string dilemma_24 {
            get {
                return ResourceManager.GetString("dilemma_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark ;Mark receives a communication that the captain of a cargo ship has contracted a highly infectious disease. The captain himself is only a carrier of the disease and is immune to the symptoms, but anybody who comes into contact with him will die. No passengers are on the ship. The ship is headed for a remote island where the captain will hand-deliver the cargo to the five islanders. The captain does not know that he is carrying the disease and has no radio on board to receive a warning. Mark takes off i [rest of string was truncated]&quot;;.
        /// </summary>
        public static string dilemma_25 {
            get {
                return ResourceManager.GetString("dilemma_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to George ;George receives a communication that the captain of a cargo ship has contracted a highly infectious disease. The captain himself is only a carrier of the disease and is immune to the symptoms, but anybody who comes into contact with him will die. No passengers are on the ship. The ship is headed for a remote island where the captain will hand-deliver the cargo to the five islanders. The captain does not know that he is carrying the disease and has no radio to receive a warning. George takes off in a [rest of string was truncated]&quot;;.
        /// </summary>
        public static string dilemma_26 {
            get {
                return ResourceManager.GetString("dilemma_26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to John ;John is driving a motorboat when he notices five swimmers drowning in the distance. If John does not drive toward them at top speed, he will not arrive in time, and all five will die. In order to drive at top speed, John must lighten the load on his boat. The only way to lighten the load is to push his passenger with his hands and cause the passenger to tumble off the back of the boat. This passenger cannot swim and will drown. If John pushes the passenger, the one passenger will drown, but John will  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string dilemma_27 {
            get {
                return ResourceManager.GetString("dilemma_27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matt ;Matt is driving a motorboat when he notices five swimmers drowning in the distance. If Matt does not drive toward them at top speed he will not arrive in time, and all five will die. In order to drive at top speed, Matt must accelerate quickly. Accelerating quickly will also cause a passenger to tumble off the back of the boat. This passenger cannot swim and will drown. If Matt accelerates quickly, the one passenger will drown, but Matt will save the five drowning swimmers. If Matt does not accelerate [rest of string was truncated]&quot;;.
        /// </summary>
        public static string dilemma_28 {
            get {
                return ResourceManager.GetString("dilemma_28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dave ;Dave is driving a motorboat when he notices five swimmers drowning in the distance. If Dave does not drive toward them at top speed he will not arrive in time, and all five will die. In order to drive at top speed, Dave must lighten the load on his boat. The only way to lighten the load is to accelerate quickly and cause a passenger to tumble off the back of the boat. This passenger cannot swim and will drown. If Dave accelerates quickly, the one passenger will drown, but Dave will save the five drown [rest of string was truncated]&quot;;.
        /// </summary>
        public static string dilemma_29 {
            get {
                return ResourceManager.GetString("dilemma_29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connor ; Connor is at a new aquarium exhibit when he sees a visitor slip on a wet floor, fall down, and break his neck. The visitor is still alive and can be safely evacuated by medics so long as he is not moved. He has fallen, however, on top of the oxygen supply line servicing five other visitors in an underwater observation pod. Without oxygen, the five visitors will soon die. If Connor does nothing the one visitor will be safely evacuated, but the five visitors in the pod will die. If Connor pushes the  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string dilemma_3 {
            get {
                return ResourceManager.GetString("dilemma_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todd ;Todd is operating the switch at a railroad station when he sees an empty, out of control boxcar coming down the tracks. It is moving so fast that anyone it hits will die immediately. The boxcar is headed towards a repairman whose leg is caught in the switch. If Todd does nothing, the boxcar will hit the repairman and then come to a stop on the empty main track where nobody else is threatened. Todd can pull a lever that will switch the tracks and release the repairman’s leg, allowing him to jump safely [rest of string was truncated]&quot;;.
        /// </summary>
        public static string dilemma_30 {
            get {
                return ResourceManager.GetString("dilemma_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luke ;Luke is operating the switch at a railroad station when he sees an empty, out of control boxcar coming down the tracks. It is moving so fast that anyone it hits will die immediately. The boxcar is headed towards five repairmen on the track. If Luke does nothing, the boxcar will hit the five repairmen on the track. Luke can pull a lever redirecting the boxcar to an empty sidetrack. However, pulling the lever will cause the switch to crush one other repairman working on the switch, who will die immediat [rest of string was truncated]&quot;;.
        /// </summary>
        public static string dilemma_31 {
            get {
                return ResourceManager.GetString("dilemma_31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alan ;Alan is operating the switch at a railroad station when he sees an empty, out of control boxcar coming down the tracks. It is moving so fast that anyone it hits will die immediately. The boxcar is headed towards a repairman whose leg is caught in the switch. Further down the main track are five more repairmen. If Alan does nothing, the boxcar will hit the one repairman and therefore slow to a stop and not hit the other five repairmen. Alan can pull a lever and release the repairman’s leg, allowing him [rest of string was truncated]&quot;;.
        /// </summary>
        public static string dilemma_32 {
            get {
                return ResourceManager.GetString("dilemma_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mike; Mike is at a new aquarium exhibit when he sees a visitor slip on a wet floor, fall down, and break his neck. The visitor is still alive and can be safely evacuated by medics so long as he is not moved. He has fallen, however, on top of the oxygen supply line servicing five other visitors in an underwater observation pod. Without oxygen, the five visitors will soon die. If Mike does nothing the one visitor will be safely evacuated, but the five visitors in the pod will die. If Mike pulls the supply lin [rest of string was truncated]&quot;;.
        /// </summary>
        public static string dilemma_4 {
            get {
                return ResourceManager.GetString("dilemma_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Justin ; Justin is driving his motorboat in the bay when he notices some swimmers in trouble. There are five swimmers drowning at the end of a narrow channel in front of Justin. In between Justin and the drowning swimmers is another swimmer who is safe and not in trouble. If Justin takes the narrow channel to the five drowning swimmers and saves them, the wake from Justin’s boat will wash over the safe swimmer, drowning him. If Justin does nothing, the five swimmers will drown and the one swimmer will remai [rest of string was truncated]&quot;;.
        /// </summary>
        public static string dilemma_5 {
            get {
                return ResourceManager.GetString("dilemma_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don; Don is driving his motorboat in the bay when he notices some swimmers in trouble. There are five swimmers drowning at the end of a channel in front of Don. To the side of the channel there is another swimmer drowning. If Don stops to save the one swimmer on the side of the channel, he will not be able to get to the five swimmers in time to save them. If Don continues to speed towards the five swimmers past the one swimmer, the one swimmer will drown, but he will reach the five swimmers in time to save  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string dilemma_6 {
            get {
                return ResourceManager.GetString("dilemma_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dennis ; Standing by the railroad tracks, Dennis sees an empty, out-of-control boxcar about to hit five people. Next to Dennis is a lever that can be pulled, sending the boxcar down a side track and away from the five people. But pulling the lever will also lower the railing on a footbridge spanning the side track, causing one person to fall off the footbridge and onto the side track, where he will be hit by the boxcar. If Dennis pulls the lever the boxcar will switch tracks and not hit the five people, and [rest of string was truncated]&quot;;.
        /// </summary>
        public static string dilemma_7 {
            get {
                return ResourceManager.GetString("dilemma_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frank ;Standing on a footbridge spanning the railroad tracks, Frank sees an empty, out-of-control boxcar about to hit five people. Frank’s leg is stuck in the railing, but next to Frank is one person who he can push, causing the one person to fall off the footbridge and onto the main track where he will be hit by the boxcar. The boxcar will slow down because of the one person, therefore preventing the five from being hit. If Frank pushes the one person, the one person will fall and be hit by the boxcar, and [rest of string was truncated]&quot;;.
        /// </summary>
        public static string dilemma_8 {
            get {
                return ResourceManager.GetString("dilemma_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evan ;Standing by the railroad tracks, Evan sees an empty, out-of-control boxcar about to hit five people. Next to Evan is a lever that can be pulled, lowering the railing on a footbridge that spans the main track, and causing one person to fall off the footbridge and onto the main track, where he will be hit by the boxcar. The boxcar will slow down because of the one person, therefore preventing the five from being hit. If Evan pulls the lever the one person will fall and be hit by the boxcar, and therefor [rest of string was truncated]&quot;;.
        /// </summary>
        public static string dilemma_9 {
            get {
                return ResourceManager.GetString("dilemma_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DilEng.
        /// </summary>
        public static string DillemFolder {
            get {
                return ResourceManager.GetString("DillemFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a valid value.
        /// </summary>
        public static string ErrorComboboxValidation {
            get {
                return ResourceManager.GetString("ErrorComboboxValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid value.
        /// </summary>
        public static string ErrorTextInputValidation {
            get {
                return ResourceManager.GetString("ErrorTextInputValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bpm.
        /// </summary>
        public static string hxmBPM {
            get {
                return ResourceManager.GetString("hxmBPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery charge.
        /// </summary>
        public static string hxmCharge {
            get {
                return ResourceManager.GetString("hxmCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heart rate.
        /// </summary>
        public static string hxmHeartRate {
            get {
                return ResourceManager.GetString("hxmHeartRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heart rate monitor is not ready.
        /// </summary>
        public static string hxmNotReady {
            get {
                return ResourceManager.GetString("hxmNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heart rate monitor ready.
        /// </summary>
        public static string hxmReady {
            get {
                return ResourceManager.GetString("hxmReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New test.
        /// </summary>
        public static string NewTest {
            get {
                return ResourceManager.GetString("NewTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next →.
        /// </summary>
        public static string NextButton {
            get {
                return ResourceManager.GetString("NextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ᛃ Jeran.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View database.
        /// </summary>
        public static string ViewDB {
            get {
                return ResourceManager.GetString("ViewDB", resourceCulture);
            }
        }
    }
}
